### ISSUE TITLE
Añadir un lugar al caer a los chasms

### ISSUE THREAD

**Issue by killer7luis** [Helixis/Paradise#1058]
No se si me explico bien, pero hacer que al caer en un chasm (esos huecos de lavaland) aparezcas en otro lugar mas profundo donde hay megafauna agresiva y dificil de esquivar, por lo menos asi si tienes suerte podrias salir de este, si es que la megafauna no te mata antes c:

Hago esta recomendacion porque ya he visto a nuevitos, veteranos y a otras personas caer en estos y me parece algo injusto que no se pueda volver

**Comment by rtlui** [comment]
Le pasa por mancos jaja

**Comment by SagaStars** [comment]
Cringe Issue.
