### ISSUE TITLE
Mover Incinerador a desechos tóxicos.

### ISSUE THREAD

**Issue by Spircen** [Helixis/Paradise#503]
Añadir el Incinerador a la sala derecha de la turbina y hacer que los desechos lleguen a una cámara de incineración en lugar de salir disparados al espacio. Me parece que lanzar basura al espacio es una de las mayores irresponsabilidades que NT podría realizar a la par que así podemos dar más uso al Incinerador y dejamos a ingeniería una tarea nueva.

**Comment by N0thy** [comment]
La cosa es que la trituradora debería de funcionar bien, porque tiene una recicladora que no funciona )¿?.
al menos como cosa extra, si se añade una incineradora, que tenga un modo seguro como le trituradora (cuando no está emageada)

**Comment by SagaStars** [comment]
Outdated.
