### ISSUE TITLE
Daño cerebral puede evitar cargos al pagar.

### ISSUE THREAD

**Issue by Spircen** [Helixis/Paradise#504]
**Issue Description**:

Cuando tienes daño cerebral y compras algo en una maquina expendedora pero te sale (You momentarily forget how to use the example vendor), te da el objeto pero no se gasta el dinero.

**What did you expect to happen**: 
Que no se efectuará la transacción al hacer el pago por dicho objeto debido a que como tal el texto dice que olvide como ocupar está maquina

**What happened instead**:
Te da el objeto pero no se gasta el dinero.

**Why is this bad/What are the consequences**:
La posibilidad de que puedas sacar cosas sin pagar.

**Steps to reproduce the problem**:
Agregar daño cerebral a un carbón y cuando efectuamos el pago hay una posibilidad de no pagar por lo que pedimos al darle con la ID

**When did the problem start happening**:
Desconozco esto, pero actualmente sigue sucediendo esto.

**Extra information**:
Sugerencia tomada de code-suggest.

**Comment by jaguar55** [comment]
No estoy seguro de si es lo mismo, pero me paso un caso similar hace una semana, 

Encontre un papel con el nombre 007 y en el aparecia un usuario y contraseña del banco, entré en la cuenta bien, y al intentar sacar dinero la maquina mando un mensaje de error diciendo que la cuenta estaba innacesible en estos momentos (o algo asi), la cantidad de dinero en la cuenta no bajaba pero si que sacaba el dinero (pudiendo sacar dinero infinito).

Hable con un admin y al final quedo la cosa en que quiza fuera un easter egg, pero ahora que veo el reporte parece un caso similar.

**Comment by SagaStars** [comment]
Outdated.
