### ISSUE TITLE
Boinas 

### ISSUE THREAD

**Issue by AniciaBelle** [Helixis/Paradise#506]
Agregar las boinas de colores:
> Azul
> Negra
> Morada
A la maquina Xtra
Asi, en mi caso, me puedo ahorrar puntos de Loadout en algo tan simple

**Comment by Spircen** [comment]
Me parece mas optimo agregarlo al hatlord. Claro, las boinas de colores son algo que no debería de requerir muchos puntos.

**Comment by N0thy** [comment]
Creo que podría codearlo.
y sobre lo de Spircen, si no me equivoco cuestan 1 punto en el loadout.... Creo.

**Comment by Spircen** [comment]
Ocuparemos tu sugerencia para testear unas cosas. Sin problemas podemos hacer este cambio.

**Comment by SagaStars** [comment]
Outdated.
