### ISSUE TITLE
Poder lanzar manualmente las pods 

### ISSUE THREAD

**Issue by Capitan-Dev** [Helixis/Paradise#513]
En resumen: hacer como CM poner un pequeño boton en las pods para poder evacuar rapido pero solo para cuando se haya llamado shuttle (aunque creo que seria mas comodo que cuando se ancle la shuttle a la estacion) y eso para poder huir in extremis mientras esos 5 xenos te pisan los talones

**Comment by Spircen** [comment]
Raro que estés por aquí. Por el momento no podemos modificar el sistema de lanzamiento de Pods culpa de que personalmente me toca ver mas de un antagonista que se queda SSD cerca de una Pod una vez cumplidos sus objetivos. Esto solamente motivaria a los jugadores a correr a la pod mas cercana y abandonar a la crew abordo. Si de por si hay que recordar a los Heads de turno constantemente que no deben de forzar el despegue de la mainshuttle antes de tiempo a no ser que exista una amenaza que pueda subir abordo.

**Comment by Capitan-Dev** [comment]
Entiendo gracias 👍

**Comment by Evankhell561** [comment]
Opino que no y aunque en código rojo podría funcionar. Esos momentos de espera antes de arranque en el que todo puede pasar son memorables.
