### ISSUE TITLE
Aumentar el tiempo de Desfribador.

### ISSUE THREAD

**Issue by N0thy** [Helixis/Paradise#514]
creo que sería buena idea poder aumentar el desfr, no creo que disminuya los casos de clonación pero creo que no sería mala idea buffearlo.

**Comment by Spircen** [comment]
Uuuuh.... ¿Te refieres a aumentar el numero de veces que un desfribilador puede hacer? ¿Aumentar su tiempo de desfribilacion? ¿O aumentar el tiempo de vida del corazón una vez se detiene para ser desfribilado?

**Comment by SagaStars** [comment]
Suponiendo que te refieres a que los cuerpos tengan un lapso mas alargado en el cual puedan ser defribilados, me parece correcto y es mas, actualemente se haya un PR en paradise sobre este tema para buffear el tiempo hasta 5m a diferencia del actual que es de 2m.

**Comment by N0thy** [comment]
Me refiero a lo que dice Saga, sí.

**Comment by SoulAnima** [comment]
La verdad es una buena idea, se supone que todos los métodos de revivir (ya sea por trasplante, usando la clonadora o el strange regent) son un ultimo recurso si no se pudo desfribilar con éxito a una persona o ha pasado mucho tiempo. El tema es que la mayoría de veces no llegas a desfribilar incluso si encontraste rápido el cadáver por que 2 minutos es realmente poquísimo tiempo y casi siempre muerto estará lejos de med

**Comment by Evankhell561** [comment]
Aun si hicieran un pr de esto lo tendra en espera mientras el pr de paradise este activo. Si fuera por mi lo subiria a 3 min.
