### ISSUE TITLE
[Feature Request] Objetos de Capellan

### ISSUE THREAD

**Issue by R31L3** [Helixis/Paradise#515]
What Does This PR Do
Propongo agregar las siguientes opciones a la Null Rod
![image](https://user-images.githubusercontent.com/62670684/77583416-cd46ce80-6ebf-11ea-8602-0eef65c4ab84.png) Unholy blessing: Igual que la Dark blessing pero parese un tentaculo de Changeling en ves de el brazo filo
![image](https://user-images.githubusercontent.com/62670684/77583442-d768cd00-6ebf-11ea-9ced-574a8b0a372e.png) Egyptian staff: misma funcionalidad que la Null Rod
![image](https://user-images.githubusercontent.com/62670684/77583280-97a1e580-6ebf-11ea-9b50-244623cfbd70.png) Holyparasite: entrega unas cartas de Tarot especiales que intentas de invocar al Holyparasite si funciona(un fantasma acepta) el capellan obtiene al Holyparasite el cual es como el Holo parasite Standard excepto no tiene los gritos, puede curar a cualquiera menos al capellan y puede destruir runas.
![image](https://user-images.githubusercontent.com/62670684/77583341-af796980-6ebf-11ea-88bc-f211ab838cf7.png) Pride-struck hammer: hace poco daño melee pero una cantidad moderada si lo tiras.

Why It's Good For The Game
Agrega variación y customización.
Changelog
cl
add: Added new things Unholy blessing, Egyptian staff, Holyparasite y Pride-struck hammer
imageadd: added some icons and images
![image](https://user-images.githubusercontent.com/62670684/77583400-c4ee9380-6ebf-11ea-84e0-2793fc3260db.png)
![image](https://user-images.githubusercontent.com/62670684/77583462-dfc10800-6ebf-11ea-82c3-b5c246362583.png)
![image](https://user-images.githubusercontent.com/62670684/77583302-a2f51100-6ebf-11ea-960f-61a7b1356405.png)
![image](https://user-images.githubusercontent.com/62670684/77583377-bbfdc200-6ebf-11ea-8171-f600370d7077.png)
/cl

**Comment by Spircen** [comment]
Suenan bien, pero únicamente tengo mis dudas respecto a darle directamente un holoparasito similar al de los antagonistas. Puede que tengamos que modificarlo un poco respecto a los limites que tenga. 

A la par que si nos apoyas enviando los DMI de cada uno de esos sprites o indicandonos el code de donde salieron nos haces las cosas mas faciles.

**Comment by R31L3** [comment]
> Suenan bien, pero únicamente tengo mis dudas respecto a darle directamente un holoparasito similar al de los antagonistas. Puede que tengamos que modificarlo un poco respecto a los limites que tenga.
> 
> A la par que si nos apoyas enviando los DMI de cada uno de esos sprites o indicandonos el code de donde salieron nos haces las cosas mas faciles.

Esos son los unicos Sprites que he visto y aqui esta el link al codigo de las armas de null rod que propuse y hasta algunas que no me decidi si proponer.
https://github.com/SolCorporation/ColonyStation/blob/7816435fe724ac34cc46db948f90e22091bc2a71/code/game/objects/items/holy_weapons.dm
