### ISSUE TITLE
[Feature request] Diario/Agenda de mano

### ISSUE THREAD

**Issue by Jinouga19** [Helixis/Paradise#525]
**Issue Description:**

Agregar un diario y una agenda de mano que no ocupe mucho espacio para que puedas apuntar cosas y no sea cutre como llevar hojas sueltas.

**What did you expect to happen:**

Que la gente lo pueda usar para rolear o para que haya momentos interesantes. Apuntar tambien cosas olvidadizas al tener tu agenda/diario a mano, cosas que te dicen por radio que luego no te acuerdas, etc...

**What happened instead:**

Apuntas cosas.

**Steps to reproduce the problem:**

Agregar una agenda y un diario para que podamos apuntar cosas.

**Extra information:**

Se me ocurrió esta idea ya que mi personaje es bastante olvidadizo

**Comment by Sauronato** [comment]
Están las notes del PDA allí puedes apuntar todo

**Comment by Jinouga19** [comment]
Pero es mas diferente y bonito lo otro..., ademas se pueden dar mas situaciones al roleo

**Comment by SagaStars** [comment]
Outdated.
