### ISSUE TITLE
Emag Limite de usos

### ISSUE THREAD

**Issue by Tilk1** [Helixis/Paradise#526]
https://github.com/Helixis/Paradise/pull/439   <-  PR en cuestion
 

En la ronda actual se desato una lluvia de OOCs quejandose que el emag esta bug y es algo injusto limitar la cantidad de uso.

Habria que llevar a cabo mas testeos para ver donde ocurre el bug pero no veo nisiquiera que valga la pena , en mi opinion este cambio debe ser revertido. 

El uso del emag crea enormes situaciones donde se expone a ser descubierto y arreglar una puerta cuesta segundos con una ingenieria competente.

**Comment by Spircen** [comment]
El problema es que si la gente se pone a dar clicks al objeto emageado el emag sigue cargando el uso. Ya lo resuelvo yo, pero no veo por que deberíamos revertir el limite de  usos de un objeto que te da un acceso total.

**Comment by Spircen** [comment]
Igualmente si comentas de quejas referente a personas quejándose de X cosa apreciaría que agregues evidencia de las quejas (capturas de pantalla), de otra forma solo es dar mas peso a algo sin bases.

**Comment by Tilk1** [comment]
Acceso total,  dejando una enorme puerta rota con luces que apuntan que hay un traidor en la estación. Que solo basta que vaya un detective y analice las huellas para darse cuenta quien fue el culpable y un ingeniero que la arregle en segundos.

La emag le agrega un factor divertido a las rondas y se puede interactuar con mil cosas. Darle 6 usos lo vuelve un item poco fiable y simplemente que no vale la pena por 6 telecristales.

Esto solo va a hacer que los traidores que quieran entrar a lugares usen el remote control que tiene usos infinitos, puedes abrir puertas sin dejar ninguna huella, puedes hacerlo desde la distancia y ademas no queda una puerta rota detras. Da mucha menos interaccion en el juego que la emag.

La puerta rota no es una ventaja para el antag, es una contra porque te delata
EDIT: adjunto las imagenes al issue

**Comment by Tilk1** [comment]
Bueno literalmente se me acaba de crashear el byond asiq rip fotos lmao

**Comment by Spircen** [comment]
Tiene 20 usos actualmente el emag y la herramienta permite a los traidores simplemente joder la estación y dar trabajo a los ingenieros a montones sin repercusión alguna si esta no tiene limites.  La idea de que la herramienta no sea infinita es para evitar que los traidores simplemente destruyan la estación por el placer de hacerlo.

**Comment by Evankhell561** [comment]
> El problema es que si la gente se pone a dar clicks al objeto emageado el emag sigue cargando el uso. Ya lo resuelvo yo, pero no veo por que deberíamos revertir el limite de usos de un objeto que te da un acceso total.

Solo resuelve esto. Creo que te dará algo de trabajo. Quizá tengas que refactorizar el como los objetos son emageables.

**Comment by Evankhell561** [comment]
> Acceso total, dejando una enorme puerta rota con luces que apuntan que hay un traidor en la estación. Que solo basta que vaya un detective y analice las huellas para darse cuenta quien fue el culpable y un ingeniero que la arregle en segundos.
> 
> La emag le agrega un factor divertido a las rondas y se puede interactuar con mil cosas. Darle 6 usos lo vuelve un item poco fiable y simplemente que no vale la pena por 6 telecristales.
> 
> Esto solo va a hacer que los traidores que quieran entrar a lugares usen el remote control que tiene usos infinitos, puedes abrir puertas sin dejar ninguna huella, puedes hacerlo desde la distancia y ademas no queda una puerta rota detras. Da mucha menos interaccion en el juego que la emag.
> 
> La puerta rota no es una ventaja para el antag, es una contra porque te delata
> EDIT: adjunto las imagenes al issue

- acceso total
- protección contra las camaras y todo lo que eso implica (ia, sec)
- todas las armas del protolate
- todos los juguetes de los null crate
- poder secuestrar la shutle 
- controlar borgs
- manipular bots
- otros mil usos
Básicamente tener una emag te brinda todo lo que puedas necesitar. Si aparte le das usos infinitos se convierte en el item que todos deben comprar. Darle solo 20 usos hace que tengan que usar la cabeza para saber donde en verdad lo necesitan.

**Comment by Evankhell561** [comment]
Agradeceria también que uses nuestro formato que para algo está. Por suerte spir te entendió pero objetivamente lo que escribiste no se entiende. Luego mezclas un reporte de bug con una solicitud. No las mezcles por favor que luego se piensa que ambas cosas fueron resultas cuando este issue sea cerrado.

**Comment by Tilk1** [comment]
Entiendo su punto de vista. Aunq para mi es por lo menos un cambio controvertido y no tan necesario en este momento. Podriamos revertirlo hasta que el bug sea arreglado? Es un item emblema de los antags y podria arruinarle a mas de uno sus planes. Al menos hasta q haya mas testeos.

![unknown (1)](https://user-images.githubusercontent.com/24284918/77858116-c1b51980-71d7-11ea-8157-7f94643e4a9e.png)

Tambien seria bueno que la emag avise cuantos usos le quedan con cada uso al propietario y cambie su sprite por la emag_broken para dar cuenta que ya fue gastada

**Comment by X404ErrorX** [comment]
Estoy de acuerdo con Nicaragua en este tema, no era necesario nerfear el Emmag, es verdad que es un item bastante fuerte pero ni por asomo te ganara una partida por si solo, siempre vas a tener que ingeniártelas de alguna manera para ganar, el emmga solo te brindara apoyo en los posibles sabotajes que quieras hacer, no esta tan estaba tan desbalanceado como nerfearlo de tal manera.

acceso total (Pero con una gran probabilidad de ser descubierto)
protección contra las camaras y todo lo que eso implica (ia, sec) (La IA detecta si alguien emmagea una cámara y puede enviar a ser a detener a quien lo haya hecho)
todas las armas del protolate (Solo si eres científico, de otra manera es complicado)
todos los juguetes de los null crate (solo si eres cargo o minero, de otra manera sera complicado)
poder secuestrar la shutle (Eso implica ser el primero en llegar a la shuttle, si alguien llega antes vas a tener que luchar, aunque este punto si te lo doy, es bastante fuerte esto)
controlar borgs (Este es un buen uso, el tema es que los borgs tampoco son tan fuertes, un flash o alguien con acceso a la consola correspondiente como IA, Rd, Cap, etc los acabara rápidamente)
manipular bots (Esto tampoco es algo tan potente)
otros mil usos (Ok)

(Todos estos usos que mencionaste solo se darán en casos muy especifico y en todos tienes una contra parte que te puede hacer perder la partida si las usas.)

Evan, por muchas cosas que haga esto no te ganara una partida por si solo, vas a tener que ingeniártelas siempre para poder lograr tus objetivos, y si te llegan a descubrir (Cosa muy probable con tal objeto) una emmag no saldrá de tu bolsillo a defenderte.

En conclusión a lo que quiero llegar es que era innecesario el cambio, el objeto estaba perfecto.

**Comment by Evankhell561** [comment]
Solo hagan el pr de revert hasta que spir arregle su mierda. Si spir logra hacer bien sus cambios se lo apruebo. Mientras cierro este issue because estan usando mal el formaro. O reportan un bug o piden un feature. No ambos.
