### ISSUE TITLE
[Feature Request] 2 Nuevos trajes espaciales

### ISSUE THREAD

**Issue by Pretherox** [Helixis/Paradise#529]
¿Sería posible añadir estos trajes espaciales especiales para heads de TG? Creo que podrían ser de utilidad para tanto el RD como HoS, dado que ambos pueden necesitar ir al espacio algunas veces y no cuentan con trajes propios como hace el capitán o CE.
El traje del RD tiene protección máxima contra explosivos, lo cual le permitiría ir incluso a recuperar bombas mal detonadas sin riesgo de ser desintegrado.
https://gyazo.com/40ad21bf96a5aaf4cc4664c3e92ed484
El traje del HoS simplemente simplemente cuenta con una protección algo mayor a la de un traje espacial de sec normal.
https://gyazo.com/081aa6e904ab9226563a84ea5230d4d0

**Comment by Spircen** [comment]
Me agrada la idea de dar un Hardsuit al departamento de ciencias, pero tendríamos que modificar los valores que ofrece este Hardsuit de otra forma estoy bastante seguro que se puede volver fácilmente una herramienta de antagonista perfecta para que simplemente corran contra su objetivo y se detonen a si mismos. Ademas de que estaría mas a favor de darles un modelo de hardsuit departamental a ciencias.

Respecto a el HoS no estoy del todo seguro respecto a darle un Hardsuit, estamos por pasar de 2 a 4 hardsuits de seguridad a la armería ademas de nuevas armas. Igualmente si nos envías directamente el archivo DMI de los hardsuits nos facilitas mas el trabajo, pero igual indicándonos de que code es lo podemos tomar. 

Es un "Si" de mi parte por que apoyo la idea de agregar el hardsuit a ciencias como herramienta departamental pero no como objeto exclusivo a un RD el cual ya puede salir al espacio con los Void NASA, y un no para el hardsuit al HoS de mi parte.

**Comment by SagaStars** [comment]
HoS implementado, el RD meh.
