### ISSUE TITLE
[Feature request] Objetivos de los roboticos, borgs

### ISSUE THREAD

**Issue by Lukaracha** [Helixis/Paradise#531]
Actualmente solo se activa y completa el objetivo de crear un borg cuando metes un cerebro en la carcasa. Si es posible creo que estaria mejor que se completara cuando terminaras de ensamblar todo el borg, aún apagado y sin cerebro, ya que sigue siendo esfuerzo y tiempo que has dedicado, y por que no siempre hay ghost para meterse en un cerebro robotico.

Parece una chorrada pero satisface ver un greentext al final de ronda y la sensación de que estás haciendo algo.

**Comment by Evankhell561** [comment]
Un borg no es un borg si no tiene cerebro. Si quitara el requisito del cerebro estariamos pagandole al robotista por desperdiciar materiales.

Cuando empecé a leerte senti que esta propuesta era solo para ganar un greentext y luego lei que era precisamente para ello. 

Si es molesto no sacar greentext porque no hay fantasmas entonces propon retirar el objetivo en otro issue.
