### ISSUE TITLE
Reporte de Bugs variados

### ISSUE THREAD

**Issue by R31L3** [Helixis/Paradise#534]
**Issue Description**:
El Clockwork Floor reemplaza el sprite del plating permanentemente.
El Clockwork Wall elimina el suelo cuando es creado.
El Lavaland Habit no muestra el sprite cuando es creado.
La puerta del mimo al ser deconstruida no devuelve el Tranquilite que la hace unica.

**Comment by Spircen** [comment]
Gracias por el reporte. Ya me pondré a trabajar en los Fix respectivos para solucionar estos errores, solo una pregunta, ¿A que te refieres con lavaland habit?

**Comment by SagaStars** [comment]
One down, 3 Left.

**Comment by SagaStars** [comment]
Outdated.
