### ISSUE TITLE
Quitar las cámaras de las duchas de Arrivals.

### ISSUE THREAD

**Issue by N0thy** [Helixis/Paradise#538]
Quitar las cámaras de las duchas de Arrivals que están puestas dentro del baño misma, a mi parecer es un poco intimidante ver una cámara mientras te das una ducha tranquila.

**Comment by Spircen** [comment]
Las cámaras de las duchas de arrivals no son las únicas que se encuentran dentro de duchas. En los baños frente al Chinese Stuff vendor de comida tiene cámaras dentro. Igualmente voy a hacer el cambio solamente para poder dar un lugar a donde esconderse a esa gente que va corriendo de las cámaras y evitar los pervertidos que ven a la gente bañarse.
