### ISSUE TITLE
[Feature request] Health Analyzer para los médicos 

### ISSUE THREAD

**Issue by SoulAnima** [Helixis/Paradise#539]
Me resulto interesante leer esto por discord (si mal no recuerdo lo comento Spircen) y quería traerlo sobre la mesa. Resulta ser debido a que los medkits ya no vienen con health analyzers los medicos no empiezan con uno y si bien es fácil conseguirlos en las NanoMeds puede que se de la posibilidad de que que no haya energía para que la maquina funcione o simplemente se destruyeron en el evento de las maquinas (o explotaron una bomba que también)
Mi propuesta es que los médicos inicien ya con un analyzer como otros jobs inician con algunas herramientas de trabajo

**Comment by Spircen** [comment]
Vale, el cambio ya esta hecho. Como tal ahora el personal que inicia con un Advanced Medikit tiene su HA dentro, hasta el momento el único que aparecía con su HA era el paramedico, con esto ya los doctores y bs no tienen que ir a tomar prestada instrumentaría.

**Comment by SoulAnima** [comment]
No sabia que el BS llevaba uno, es bueno saber. Gracias por responder y todo
