### ISSUE TITLE
Mover la oficina del payaso y el mimo a otro lugar

### ISSUE THREAD

**Issue by smolkot** [Helixis/Paradise#550]
Queria ver si se puede mover la oficina del payaso y mimo a otro lugar, preferiblemente arrivals, actualmente el lugar que tienen es horrible ya que la nueva area de ejercicio esta jodidamente fea

**Comment by Dapple27** [comment]
No se tu, pero no creo que haya mucho espacio en arrivals, talvez se pueda quitar el checkpoint y reducir el tamaño de el jardin y el del tool storage

**Comment by N0thy** [comment]
Diría del tool storage, pero del ¿jardín? no lo veo viable.

**Comment by lharmonyl** [comment]
Segun mis testeos de mapa, entran las dos en la oficina vacante una a la par de la otra

**Comment by Evankhell561** [comment]
Mover las oficinas de esos dos porque tienen un gym adelante me parece una tontería en especial porque ninguno usa su oficina. Peero son libres de mudarse si quieren (digo de hacer el pr de mapeo)

**Comment by Pretherox** [comment]
porqué no simplemente, en vez de poner esas pedazos de ventanas que ocupan una casilla entera para el gimnasio, simplemente se pone una pared de una plancha de cristal y puertas correderas como las de las ventanillas de cocina?

**Comment by smolkot** [comment]
queria moverlo en la sala esa que esta vacia que nadie mueve, el problema es que no se mapear, also mover algo ahi

**Comment by AsrielFBI** [comment]
> 
> 
> queria moverlo en la sala esa que esta vacia que nadie mueve, el problema es que no se mapear, also mover algo ahi

Si me dices donde lo quieres te lo mappeo. O incluso si quieres te enseño a mappear btw.

**Comment by SagaStars** [comment]
Rotación de mapas.
