### ISSUE TITLE
[Bug report] Mesas de herramientas de cirugía

### ISSUE THREAD

**Issue by SoulAnima** [Helixis/Paradise#554]
**Issue Description**:
Varios notamos varios problemas con las nuevas mesas de herramientas para med:

- Falta una de las herramientas, el surgical drill.
- A veces cuando vas a devolver una herramienta a la mesa, te dice que ya esta en la misma y que el lugar esta ocupado cuando en realidad esa herramienta no esta
- La ventana emergente por defecto es muy pequeña, lo que lo hace molesto a la hora de usar 

**Why is this bad/What are the consequences**:
Arruina un poco la idea original de la mesa, haciendo que sean incomodas o in-practicas y que varios médicos decidan usar las bolsas en su lugar.

**Comment by Spircen** [comment]
Vale, reviso en la semana que onda con todos estos problemas.
