### ISSUE TITLE
[ Feature Request ] Ze Odd Blood Falls Into The Chasm

### ISSUE THREAD

**Issue by BLKYogurt** [Helixis/Paradise#558]
So,
Esto se centra en lo que post-vencer un slaughter demon o uno atrapado en otro Z-Level intentando seguir [Redacted] persona. 
**_Se podría hacer que entrar en Blood Crawl no puedas ''caer'' en un Chasm?_** 

Técnicamente pasas por encima pero como si cayeras dentro, tienes como 3 segundos antes caer directo donde te detecta como si pisaste dicho tile, And boom, you're dead.
El cambio solo afecta 2 escenarios, Sector 5/Lavaland, Gateway Hotel/Habitacion Mago (cuz' chasms)

**Comment by Evankhell561** [comment]
Alguien que me traduzca lo que dice este man. Porfa.

**Comment by Spircen** [comment]
Osea la madre que genera los tendrils de lavaland, el precipicio ese. Que no te caigas cuando estes en la dimensión de los Blood Deamons y cosas así.

**Comment by SagaStars** [comment]
Outdated.
