### ISSUE TITLE
[Feature request] Añadir algunas cosas para el medico de seguridad

### ISSUE THREAD

**Issue by lharmonyl** [Helixis/Paradise#560]
La idea es añadir en su lugar de trabajo las siguientes cosas:

Silla de oficina
Maquina para venta de medicamentos
Caja con bolsa para cadaveres
Una chaqueta de fuerza en la sala de ejecuciones o donde el medico
Una desfibrilador en la taquilla

**Comment by Spircen** [comment]
Todos los cambios que propones me parecen correctos. Hoy hago el PR para agregar esto, como detalle solamente tenemos que borrar una NanoMed Plus de Medbay para darla al Brig Physician y asi no simplemente agregar mas medicamentos que de por si ya dan bastantes cosas estas cosas.

**Comment by lharmonyl** [comment]
> 
> 
> Todos los cambios que propones me parecen correctos. Hoy hago el PR para agregar esto, como detalle solamente tenemos que borrar una NanoMed Plus de Medbay para darla al Brig Physician y asi no simplemente agregar mas medicamentos que de por si ya dan bastantes cosas estas cosas.

me parece correcto, gracias
