### ISSUE TITLE
[Feature request] Añadir 2 item nuevos en maquinas

### ISSUE THREAD

**Issue by lharmonyl** [Helixis/Paradise#561]
Añadir en la maquina de seguridad el modificador kit del stun baton. Creo  se llama scifikit
Añadir en la maquina de cargo la que vende banderas, el kit para la silla de ruedas de oro. Creo que se llama voxcaster_fluff aun que no estoy seguro

**Comment by Spircen** [comment]
En cuanto pase un PR de Balance a las Vending Machines que cree me parece bien agregar estos cambios.

**Comment by Evankhell561** [comment]
> En cuanto pase un PR de Balance a las Vending Machines que cree me parece bien agregar estos cambios.

si trabajarás en esto te advierto que dependiendo de como se vea el stunbaton con la skin pasa o no pasa. Sobre la silla de ruedas.... si es una silla de ruedas de oro deberia fabricarse con oro (o si las sillas se piden en cargo entonces añadir un pedido de una silla dorada)
