### ISSUE TITLE
[SUGG]Beebsky Estacion Rusa.

### ISSUE THREAD

**Issue by NervalARS** [Helixis/Paradise#562]
En la USSP del sector 6 (la estacion rusa) hay un beepsky que puede meterte permastun y acabar matándote ya que te estunea unos 6 segundos y tambien te golpea (harm). 

A diferencia de los demás enemigos que se pueden encontrar en la estación este con cometer un error te mata si o si ya que una vez estuneado no podrás volver a levantarte del suelo lo que causara una muerte lenta y muy frustrarte.

Básicamente pediría que se removiera este enemigo de la estación o que funcionara como los beebsky de la estacion NT, que una vez estuneado te atara y te dejase en paz.

**Comment by Spircen** [comment]
Entiendo el problema con este enemigo, como tal cuentas con una EMP Granade para deshabilitarlo pero sin duda alguna el permastun no es algo positivo dentro del juego. Voy a comentarlo con los otros Devs y ver si podemos ya sea modificar el tiempo entre stuns para que no sea instakill al primer error con el.

**Comment by SagaStars** [comment]
Outdated.
