### ISSUE TITLE
Jaws of Live estan rotas

### ISSUE THREAD

**Issue by NervalARS** [Helixis/Paradise#564]
Os cuento, estas cosas ya no son algo exclusivo de ingeniería, en cada ronda en la que estoy al cabo de la hora todo santo tiene esta cosa que puede abrir cualquier puerta. Básicamente es como un emag pero legal ademas de poderse producir en masa. 

Solicito que su uso este restringido a ingenieria y que aparezcan en cajas en el protolathe, las cuales solo el CE tenga acceso.

Hay que limitar un poco el acceso a esta herramienta tan poderosa.

**Comment by Evankhell561** [comment]
El power gaming está prohibido por los admin, creo que a duck le banearon por abusar de la ion rifle para abrir puertas o le dieron advertencias para que deje de hacerlo y por lo que he visto no hay bans por la jaws. Igual preguntaré a los admis si es cierto pero si alguien quiere hacer power gaming lo hará de una forma u otra y las jaw no son el unico metodo de entrar a donde no te llaman.

**Comment by NervalARS** [comment]
EL ion rifle esta menos roto que la jaw, yo ha en multiples ocasiones lo e usado para abrir puertas y necesitas de varios disparos, ademas de haber el riesgo de electrocutarte.

**Comment by Evankhell561** [comment]
Cerado por estar denegado
