### ISSUE TITLE
[Bug report] Laptop de  Records HoP

### ISSUE THREAD

**Issue by Spircen** [Helixis/Paradise#565]
Maquinaria de HoP permite asignar Syndicate Officers, Navys y mas.

**What did you expect to happen**: 
Poder modificar registros de un tripulante

**What happened instead**:
Me dejaba asignar a rangos bastante mas altos a el poder de un capitan.

**Why is this bad/What are the consequences**:
Podemos tener Navy Officers de a gratis

**Steps to reproduce the problem**:
Abrir laptop de records 

**When did the problem start happening**:
Despues del update del 04/04/2020

**Extra information**:
Una imagen que tomo SrReptile pero es un flojo para armar un reporte. 

![image](https://user-images.githubusercontent.com/46639834/78622294-683d9200-784a-11ea-828e-d9828ce8deb5.png)

**Comment by Evankhell561** [comment]
Intenta revisar si sigue sucediendo en el repo actualizado.

**Comment by SagaStars** [comment]
Outdated.
