### ISSUE TITLE
[SUGG]Vox Armalis

### ISSUE THREAD

**Issue by NervalARS** [Helixis/Paradise#566]
Básicamente solo sugiero habilitar a los vox armalis como una raza jugable, es lo mismo que un vox normal pero su sprite esta 10 veces mejor, ademas de ser la única raza de un tamaño superior.

**Comment by Evankhell561** [comment]
no está habilitado precisamente porque su tamaño lo hace tener problemas con la ropa.

**Comment by SagaStars** [comment]
Mala idea.
