### ISSUE TITLE
[Feature Request] Petacas para Cinturones.

### ISSUE THREAD

**Issue by AinaryuFenris** [Helixis/Paradise#567]
Para aquel spessman que necesita un sorbito para aguantar a su jefe, o para el jefe que solamente quiere despejar un poco la cabeza de la tripulación sin ser visto tomando directamente de una botella.

La idea de la petaca en primera instancia se refiere a que una petaca pueda ser añadida como accesorio o como item a cualquier cinturón y prenda que se considere que tenga un cinturón. Podrá contener cualquier tipo de petaca.

Adjunto una imagen de ejemplo de una petaca usada como hebilla de cinturón:
![imagen](https://user-images.githubusercontent.com/63303806/78684008-47c81300-78f0-11ea-94ec-afbc0d969220.png)

**Comment by Spircen** [comment]
Uh... solo para aclarar. ¿Quieres que vaya en la zona de belt? ¿O quieres que se pueda pegar al jumpsuit como accesorio?

**Comment by AinaryuFenris** [comment]
> 
> 
> Uh... solo para aclarar. ¿Quieres que vaya en la zona de belt? ¿O quieres que se pueda pegar al jumpsuit como accesorio?

Sinceramente no estoy seguro, pero cualquiera de los dos está bien. 
Quizás como **Accesorio** puede que le de más juego, pero es ya **_a decisión de quien lo quiera codear_**.

**Comment by SagaStars** [comment]
No hay cinturones.
