### ISSUE TITLE
[Bug report]Sprite broke

### ISSUE THREAD

**Issue by SpiritualShadow** [Helixis/Paradise#570]
**Issue Description**: Al pegarse a uno mismo en un lugar sin gravedad tu sprite se moverá un poco más arriba, tanqueando el daño con items de curación y armadura puedes sacar a tu sprite de tu pantalla, puedes meterte golpes con cosas como peluches que no hacen daño para abusar esto al máximo.

**What did you expect to happen**: No sé, pegarme por que estaba aburrido

**What happened instead**:Empecé a levitar ooo

**Why is this bad/What are the consequences**:No creo que tenga que mencionar el por que una persona pudiéndote pegar con el hitbox en otra habitación es malo

**Steps to reproduce the problem**: Encontrar una zona sin gravedad y pegarte repetidas veces, preferiblemente con un objeto que no haga daño.

**When did the problem start happening**: Ni idea, desde la última update supondré.

**Extra information**:También hay un bug que el blueshield no puede usar el legsweep pls fix
![Screenshot_5671](https://user-images.githubusercontent.com/63086609/78709073-71317080-78e9-11ea-8557-2912c8cccf28.png)

**Comment by SagaStars** [comment]
QUE.
![image](https://user-images.githubusercontent.com/55407528/78709675-0d577980-78e2-11ea-8e51-858be3406542.png)

**Comment by Dapple27** [comment]
wtf

**Comment by AinaryuFenris** [comment]
El buen viaje espiritual pero al revés.

**Comment by SagaStars** [comment]
Outdated.
