### ISSUE TITLE
[Feature request] Mejorar el bscqc

### ISSUE THREAD

**Issue by SpiritualShadow** [Helixis/Paradise#573]
El Bscqc es un arte marcial que te hace peor que un asistente actualmente, necesitas 6 golpes consecutivos que si tardas más de 10 segundos entre golpe se reinicia todo gracias al condenado mcloud y su pr https://github.com/ParadiseSS13/Paradise/pull/12591, y pensarías que ya una vez haces eso sería la batalla ganada, pero no, por que a los diez segundos también se regenerará tooodo el daño que le hiciste, cosa que es básicamente un stun baton pero tienes que pegar 6 veces en un lapso de tiempo de menos de 10 segundos entre golpe y golpe, en el que el asistente puede directamente meterte un disarm o un harm con weakened, que lleva a mi siguiente punto, el blueshield no tiene ni eso, sus disarms no tiran pushed y sus golpes no tiran weakened, la única manera que tienes de stunear a alguien en pleno combate sin tener que hacerle un combo del mortal kombat mientras esquivas todos sus ataques era el legsweep que sacaron, que requería que te tiraras al piso y te quedaras inmóvil siendo divertido ya que era dar o morir.  También pensarías que el daño de stamina *podría* ser útil si el tipo ya está con mucho daño para poder tirarlo fácilmente de dos golpes, pero nope, gracias al pr ya mencionado el daño de stamina ni se acumula con el daño bruto ahora. El disarm como desarmar nunca lo probé, es básicamente inútil intentar desarmar a alguien cuando puedes stunearlo logrando lo mismo pero mejor, sin mencionar que muchas de las veces que desarmar a alguien se vuelve una prioridad real como un tipo con una double esword el block chance del arma entra en eso, así que utilidad alguna no le vi en todo este tiempo desde que lo metieron. Luego está el block chance, que creerías que puede ser útil para proteger heads durante un tiroteo o algo así, tampoco. El block chance solo bloquea melee, y si te golpean en melee te quieren matar a ti, no al head. Y si estás en throw mode no puedes atacar que es lo que haces lógicamente cuando alguien te está apuñalando. El arte marcial no tiene consistencia alguna, no se le encuentra razón y se lo podrían dar a cualquier persona y nadie notaría la diferencia, sugiero revertir el PR de stamina y devolverle alguna manera de stunear, o borrarlo de una, por que un arte marcial no se supone sea un downgrade.

**Comment by Evankhell561** [comment]
1. No le daremos a nadie un arte marcial que le permita bloquear balas.
2. El daño de stamia le permite realentizar a alguien y dar chance a escapar al blue o al head. 
3. El bs ya tenia equipo para progerse a el y al head.
4. no le daré a nadie una forma de stunear instantaneamente más allá de un disarm. 
5. 10 segundos es mucho tiempo pudes hacerle lo que quieras en ese tiempo y solo nitas mantener el combo stamia+daño (considerando que tiene daño aumentado cuando está en el suelo) y nunca se va a levantar ni defenderse de ti (aunque sea una manera lenta de matar pero en 10 segundos puedes ponerle unas esposas, en cambio con un disarm no da tiempo para ello.
6. luego del primer golpe de stamia resulta facil meter los otros. 
7. ¿te parece consistente que el blue tenga que tirarse al piso y quedarse inmovil para proteger a alguien? hablas de una fantasia de proteger pero no veo como eso tenga que ver con proteger a alguien más bien es esperar a que alguien venga a por ti.
8. ningun arte marcial que le demos a la crew estará destinado a que puedas ganarle facilmete a alguien
9. en lo unico que tienes un punto en todo lo que has dicho es en "creo que es un downgrade" no soy experto en combate, quizá lo sea y si es asi estoy deacuerdo en removerlo o buscar alguna cosilla que lo haga más interesate (spolier; no será nada espectacular nunca). Esperaria el feedback de la gente en este tema.

**Comment by SpiritualShadow** [comment]
1-Cool, pero mi punto era que bloquear ataques no es muy útil por que no puedes contraatacar
2-El debuff de velocidad del daño de stamina no se siente hasta el cuarto golpe, al menos que estés en persecución que no es trabajo del blue.
3-Válido
4-Entonces devuelvan el disarm normal con su RNG, sus disarms actuales no hacen nada más que daño y quizás sacarle el arma.
5-El problema es que es muy díficil darle 6 golpes melee a alguien sin que te dejen en crit o te stuneen ellos mismos, claro, tienes tu baton pero eso hace el brillo principal del arte marcial completamente situacional y rara vez usado en combate real.
6-Como dicho, el daño de stamina que hace el primer combo es casi nulo, no se siente para nada en un combate.
7-Es un movimiento, no se queda tirado, le mete el stun y se levanta o falla el stun y se levanta, usado con una hotkey a rest como cualquier otro code termina siendo más útil de lo que parece, y al estar tirado en el piso un atacante puede pensar que estás indefenso, prioritizandote como objetivo antes que a alguien huyendo.
8-Fácilmente a alguien puedes ganarle, si no tienen armas ni stuns, para lo único que sirve actualmente es peleas de bares, nunca entra en juego realmente al momento de proteger a un head contra cosas como nukies con eswords o así.
9-El downgrade viene de la parte de que para stunear ocupas 6 golpes consecutivos, mientras que el combate normal puede ser el primero con tal que tengas suerte.

**Comment by Evankhell561** [comment]
4-Entonces devuelvan el disarm normal con su RNG, sus disarms actuales no hacen nada más que daño y quizás sacarle el arma.

el rng ahora está en quitar el arma (e incluso es más probable que el tumbar con el disarm) 

7-Es un movimiento, no se queda tirado, le mete el stun y se levanta o falla el stun y se levanta, usado con una hotkey a rest como cualquier otro code termina siendo más útil de lo que parece, y al estar tirado en el piso un atacante puede pensar que estás indefenso, prioritizandote como objetivo antes que a alguien huyendo.

No digo que no sea util o que no sea un buen movimiento. Solo no creo que tengas razón al decir que este movimiento cumpla con la fantasia de lo que es un BS. (parece más el arte marcial borracho)

> 8-Fácilmente a alguien puedes ganarle, si no tienen armas ni stuns, para lo único que sirve actualmente es peleas de bares, nunca entra en juego realmente al momento de proteger a un head contra cosas como nukies con eswords o así.

bien, ese es el punto, no le daré una ventaja a nadie que pueda hacer que desarmado le ganes a alguien con una espada laser (y aun asi es más probable que el blue le robe el arma al nuke mientras ejecutasu combo de presión que el que alguien pueda tumbar al nuke con disarm). Y justamente está enfocado a esto, a que puedas ganarle a alguien que venga desarmado contra ti. Este punto demuestra que está siendo lo que se supone que deba hacer. Si no te gusta lo entiendo,

> 9-El downgrade viene de la parte de que para stunear ocupas 6 golpes consecutivos, mientras que el combate normal puede ser el primero con tal que tengas suerte. 

Entiendo. Como digo no soy experto en combate y quizá tengas razón.

**Comment by SpiritualShadow** [comment]
Todo eso suena súper bien en papel, pero en práctica te das cuenta de que lo más simple es usar el stunbaton, incluso para gente desarmada por que la idea no es dañarlos pero el disarm pega por alguna razón. Si el punto entero del arte marcial es defender por que no lo hacen en torno a eso en vez de una cosa graciosa para ganar peleas de holo. Nadie dice que sea algo op, pero tampoco es nada interesante y está por estar.  También quiero saber que juego juegas que te puedes acercar a un tile de un nukie sin que te dispare el o sus compañeros con las armas que pueden bajarte a crit en 2 segundos.

**Comment by Evankhell561** [comment]
> Todo eso suena súper bien en papel, pero en práctica te das cuenta de que lo más simple es usar el stunbaton, incluso para gente desarmada por que la idea no es dañarlos pero el disarm pega por alguna razón. Si el punto entero del arte marcial es defender por que no lo hacen en torno a eso en vez de una cosa graciosa para ganar peleas de holo. Nadie dice que sea algo op, pero tampoco es nada interesante y está por estar. También quiero saber que juego juegas que te puedes acercar a un tile de un nukie sin que te dispare el o sus compañeros con las armas que pueden bajarte a crit en 2 segundos.

yo no he dicho que vayas a usarlo para pelear con un nuke. tu eres el que ha puesto ese ejemplo. Si un arte marcial es lo suficientemente bueno como para que lo prefieras a usar tu stunbaton entonces es un arte marcial demasiado bueno para encontrarse normalmente en el juego.

**Comment by SagaStars** [comment]
Muy bonita su pelea de judo verbal, pero porfavor escriban en parrafos separados que mis neuronas no dan para tanto.

**Comment by SagaStars** [comment]
Done.
