### ISSUE TITLE
[Feature Request] Lollipops en la boca.

### ISSUE THREAD

**Issue by AinaryuFenris** [Helixis/Paradise#579]
Para todo el Spessman que solo quiera tener algo que mordisquear en vez de fumar.

Esta sugerencia consiste en poder equiparse lollipops/suckers/piruletas en el slot de la boca.

Conforme pase el tiempo, los componentes de ese lollipop se consumirán poco a poco hasta solo quedar la vara del lollipop.
Alternativamente, se podrá hacer alt-click para mascar el lollipop en la boca (Look ma, no hands!) y podría llevar...quizá de 2 a 5 mordiscos.

**Comment by SagaStars** [comment]
Buena feature request, tratare de llevarla a cabo.

**Comment by Evankhell561** [comment]
Aja pero creo que no hay "piruletas" en nuestro code, no deberías pedir que añadan las piruletas al juego antes de pedir que las puedas llevar en la boca?


-aca es donde me dicen que sí existen en nuestro code-

**Comment by AinaryuFenris** [comment]
> 
> 
> Aja pero creo que no hay "piruletas" en nuestro code, no deberías pedir que añadan las piruletas al juego antes de pedir que las puedas llevar en la boca?
> 
> -aca es donde me dicen que sí existen en nuestro code-

A menos que tengan diabéticos en Hispania, lo hay en Para.
![imagen](https://user-images.githubusercontent.com/63303806/79079814-a129ab00-7d11-11ea-9bf2-f8704efe399c.png)

**Comment by killer7luis** [comment]
![604819561723723786](https://user-images.githubusercontent.com/84632338/130180342-08343218-4bfe-4dd8-a225-d2068f80797c.png)

**Comment by Evankhell561** [comment]
estoy trabajando en un proyecto con un nombre similar a este pr, pensé que esta notificacion era por mi trabajo (notificacion por este pr)... Cabe destacar que con 4 meses trabajando en ese proyecto acabo de descubrir que significa Lollipop.

**Comment by SagaStars** [comment]
Outdated.
