### ISSUE TITLE
[Feature request] Sleep

### ISSUE THREAD

**Issue by SpiritualShadow** [Helixis/Paradise#581]
Añadir que al darle al verbo sleep en vez de que te duerma por cierto tiempo te duerma hasta que le des de nuevo o alguien más te despierte, para darle un uso más de rol.

**Comment by SpiritualShadow** [comment]
Le di a enter por accidente y lo subí en blanco XD

**Comment by N0thy** [comment]
Oh, oh, y si eso... que tenga tiempo mínimo de estar dormido.
Es decir, si te duermes, no al 0,5 segundos puedas levantarte, si no deba de pasar como 30 segundos o así hasta que vuelvas a poderte despertar.

**Comment by SagaStars** [comment]
Outdated.
