### ISSUE TITLE
[Feature Request] 2 Sugerencias para el Bar

### ISSUE THREAD

**Issue by AinaryuFenris** [Helixis/Paradise#583]
Para el Spessman que quiere tener una enorme reserva y quiera enfriar sus bebidas:

Estas sugerencias consisten en lo siguiente:

- Sugerencia 1: Añadir un barril vacío, o en su defecto, una manera más fácil de gestionar los contenidos de este a gran escala, ya que son 1000 unidades y el máximo que puede tener un bartender es su coctelera de 100u y una Beaker de 100u.

Alternativamente, la posiblidad de conectar los toneles a los dispensadores para rellenarlos con mayor comodidad y tener una reserva preparada. (El Rainbow juice es muy famoso y hacer exactamente 50u cada vez es tedioso as heck.)

________________________________________
- Sugerencia 2: Añadir una forma más asequible de enfriar las bebidas.

Dos de las recetas menos preparadas son Applejack y Jackrose, ambos se prepararan enfriando la Sidra/Cider a 270K, o lo que serían -3ºC. La forma más asequible actualmente es usando el Chem Heater de Química para enfriar aquel componente, pero eso se hace tedioso a la larga y no estaría mal tener una forma de al menos enfriar las bebidas sin atosigar al pobre químico y sin quitarle sus Heater, los cuales son imprescindibles.

Alternativamente, podría cambiarse la receta a simplemente "Cider + Ice".

**Comment by Spircen** [comment]
Me parece bien la idea de expandir el contenido de la coctelera es un objeto exclusivo del bartender que se puede solicitar por cargo pero no se puede fabricar aumentar su capacidad a la de una cantidad mayor podría hacerlo un item bastante útil.  

Respecto a la segunda sugerencia me imagino podríamos darle una maquina igual al chem heater al Bartender únicamente con un sprite distinto y así evitar el tema del metajuego.

**Comment by AinaryuFenris** [comment]
Uf, ahora que decis "Fabricar", me viene a la cabeza... ¡Cocteleras de distintos materiales y capacidades!

**Comment by SagaStars** [comment]
Outdated.
