### ISSUE TITLE
[Bug Report] Errores menores en las bebidas

### ISSUE THREAD

**Issue by AinaryuFenris** [Helixis/Paradise#584]
**Issue Description**:

Esta sección será actualizada conforme descubra más bebidas con errores. 
Todos estos errores son meramente **cosméticos**:

La Bebida "Erika Surprise" no solo aparece como "What" si no que utiliza el sprite de Cider/Sidra.

Ciertas bebidas exclusivas de Hispania contienen mensajes de mezcla en minúsculas y nombres en minúsculas. (What's up, soy un grammar nazi)

**Why is this bad/What are the consequences**:

Los comensales del bar no confían en un vaso de What, además de que algunas bebidas no tienen un sprite propio y aparecen como un mero vaso con un color oscuro, lo que obliga a prestar las Sunscanners para escanear los vasos y confirmar que es una bebida normal y corriente.

**Extra information**:

Viva el bar.

**Comment by Evankhell561** [comment]
> Ciertas bebidas exclusivas de Hispania contienen mensajes de mezcla en minúsculas y nombres en minúsculas. (What's up, soy un grammar nazi)

agradecemos este reporte pero agradeceriamos más si nos reportaras cuales bebidas y cuales errores. así no no nos ponemos a buscar en el code.

**Comment by SagaStars** [comment]
Outdated.
