### ISSUE TITLE
Añadir mas armas y municion balistica en la armeria

### ISSUE THREAD

**Issue by lharmonyl** [Helixis/Paradise#589]
La idea seria añadir:

4 Pistolas que no sean la traitor para evitar confusiones
4 Cargadores
3 Metralletas WT-550 Auto Rifle
3 Municiones de esa WT-550 Auto Rifle

**Comment by Evankhell561** [comment]
Las armas balisticas por balance y tematica están limitadas para la crew ordinaria. Ya hemos expandido la variedad y cantidad de armas balisticas. y posiblemente expandamos esa cantidad pronto en una expansion de la armeria propuesta en #532, pero con el mapa actual esto no sucederá. Y no se hará solo porque sí.
