### ISSUE TITLE
Quitar los antagonistas para los head

### ISSUE THREAD

**Issue by lharmonyl** [Helixis/Paradise#592]
La sugerencia es muy simple, que los head no puedan ser antagonistas o implante de loyal, porque esta bien si sale un RD traitor el cual hace traitor a la AI y a los borg cuando hay 50 jugadores, pero si lo hace cuando hay 10 y no hay seguridad, genera desbalance en 
la partida

**Comment by Evankhell561** [comment]
1. Un head antag en low pop representa o una partida rápida o una partida donde el antag tiene tanta ventaja que puede rolear ser el malo sin la preocupación de huir de sec todo el rato. En ambos casos no es tan grave. 
2. Que sea una victoria casi segura para el antag no significa quela crew pierda. El greentext del antag no esla derrota de los otros jugadores.
3. Tener la posibilidad de que tu jefe sea malo obliga a la crew a supervisar a su jefe y no confiar en cada cosa que haga. El no saber si es un mal head como jugador o es un head antag da mucho sabor al juego.
4. La mejor forma de combatir a un head antag es que se llenen los puestos de comando. Quitarlo seria quitar otro incentivo a que la gente juegue puestos de responsabilidad.
5. Hace que sec tenga que considerar el sop y la ley más a rajatabla hace que tengan que pensar más.
La unica razón que veo para quitarla es que la tienen más fácil que el resto de la crew para obtener accesos y demás pero aún así la gente le permite a su jefe abandonar el departamento todo el rato y ni se inmutan por su ausencia. Eso debe cambiar. A menos que tengas un buen argumento esto no va a suceder.

**Comment by lharmonyl** [comment]
> 
> 
>     1. Un head antag en low pop representa o una partida rápida o una partida donde el antag tiene tanta ventaja que puede rolear ser el malo sin la preocupación de huir de sec todo el rato. En ambos casos no es tan grave.

**El problema del punto 1 es lo equivalente a jugar un juego con trucos de inmortaldiad porque sabes que nadie te va a pegar y si lo hacen, es validhunter**
> 
>     2. Que sea una victoria casi segura para el antag no significa quela crew pierda. El greentext del antag no esla derrota de los otros jugadores.

**Es victoria segura y mas sabiendo la falta de seguridad siempre, pero peor aun que un rd haga traitor a una ia y a borgs. Sigue siendo 0 gracia para el rol**
> 
>     3. Tener la posibilidad de que tu jefe sea malo obliga a la crew a supervisar a su jefe y no confiar en cada cosa que haga. El no saber si es un mal head como jugador o es un head antag da mucho sabor al juego.

**Eso nunca va a pasar, la gente hace tiempo que no tiene miedo a su jefe ni siguen la cadena de mando en la mayoria de casos**
> 
>     4. La mejor forma de combatir a un head antag es que se llenen los puestos de comando. Quitarlo seria quitar otro incentivo a que la gente juegue puestos de responsabilidad.
> 
**Eso no ayuda porque tambien saldran antag**

>     5. Hace que sec tenga que considerar el sop y la ley más a rajatabla hace que tengan que pensar más.

**Totalmente sin sentido este punto**

**Comment by Evankhell561** [comment]
> **El problema del punto 1 es lo equivalente a jugar un juego con trucos de inmortaldiad porque sabes que nadie te va a pegar y si lo hacen, es validhunter**

Segun planteas esto hispania tiene un problema administrativo. deberias informarles de esto. Que alguien tenga la oportunidad de jugar con una gran ventaja no hace que la experiencia para los demás sea inherentemente mala. Esto no es un shooter. una victoria para el antag no significa que sea uan derrota pra la crew. 
 
> **Es victoria segura y mas sabiendo la falta de seguridad siempre, pero peor aun que un rd haga traitor a una ia y a borgs. Sigue siendo 0 gracia para el rol**

no es necesariamente bueno para el rol pero tampoco es malo para el rol, abre un abanico de posibilidades y depende de nuestros jugadores aprovecharla.  

> **Eso nunca va a pasar, la gente hace tiempo que no tiene miedo a su jefe ni siguen la cadena de mando en la mayoria de casos**

que aprendan a perder el miedo, tu no pareces tenerlo entonces aplica lo de supervisar a tu jefe, da el ejemplo

> **Eso no ayuda porque tambien saldran antag**

no peor no será una victoria facil con otros heads a bordo. 

> **Totalmente sin sentido este punto**

He visto a secs haciendo todo lo que diga un head sin siquiera pensar en que estos son antags, imagina si le damos a todos mindshield. En fin, esto no va a suceder. Sin embargo quizá pueda solucionar el problema de fondo de alguna otra forma.
