### ISSUE TITLE
[Bug] arreglar el tema de las adicciones respecto al tabaco y alcohol.

### ISSUE THREAD

**Issue by Fretxiz** [Helixis/Paradise#596]
El otro dia estaba muy a gusto como de costumbre y prendo un cigarro y al primero que fumo nisiquiera sin terminarlo me produce adiccion al tabaco, antes necesitabas de muchos cigarros para ser adicto, ahora es solo con uno, pongan un punto medio xd

Y respecto al alcohol, lo mismo, con solo un vaso de cualquier cosa te vuelves adicto.

**Comment by Dapple27** [comment]
las adiciones es cosa de para, evan dijo que se quedaran unos días, talvez hasta que termine la pandemia
![image](https://user-images.githubusercontent.com/43283605/79077846-32792d00-7cd2-11ea-9d54-d0fda97a9fc1.png)
 

(bueno no xd) esto es lo que dijo en realidad
![image](https://user-images.githubusercontent.com/43283605/79077901-9bf93b80-7cd2-11ea-8e43-64d473fdad82.png)
