### ISSUE TITLE
[SUGG]Shadowling

### ISSUE THREAD

**Issue by lharmonyl** [Helixis/Paradise#638]
No se si hay ya un request sobre esto. Pero dejo mi propuesta con el fin de no quitar antagonista pero darle mas ventaja a la tripulacion de combatirlo:

**Actualmente**: Cuando examinas a una persona sale : Their features seem unnaturally tight and drawn. Pero si el jugador tapa su cara, ya no sale eso. Siendo la unica forma de indentificar esclavos

**Solucion**: Que con cara oculta o no, siga dicendo esa descripcion. Tambien añadir algun HUD para medicos y poder indentificar al enfermo como ocurre con los xenos

**Actualmente**: Apagar luces tiene un cd de 15 seg

**Solucion**: Subirlo a 30

**Actualmente**:  El shadowling recibe un daño casi ridiculo de fuentes de luz. Es algo testeado por varios jugadores. Desconozco cuanto daño recibe por segundo de luz, pero es algo ridiculo 

**Solucion**: Que recibe mas daño de todas las fuentes de luz. Que tenga mas cuidado a la hora de dar pasos por la luz o acercarse a una bengala o similares.

**Comment by Spircen** [comment]
Ya hicimos las pruebas respectivas con este antagonista. Si vamos a modificar algunos CD y el daño que toma por fuentes de luz que no puede apagar como una flare. Gracias por el reporte y para el parche que viene el 3 de Mayo podrías ver los cambios reflejados.

**Comment by lharmonyl** [comment]
> 
> 
> Ya hicimos las pruebas respectivas con este antagonista. Si vamos a modificar algunos CD y el daño que toma por fuentes de luz que no puede apagar como una flare. Gracias por el reporte y para el parche que viene el 3 de Mayo podrías ver los cambios reflejados.

Lo ideal tambien seria algo para poder sacar a los slaves de ese estado, al final hay que pensar que en una pasada, te encuentras con 28 jugadores antagonistas contra 3 en seguridad

**Comment by Evankhell561** [comment]
> Lo ideal tambien seria algo para poder sacar a los slaves de ese estado, al final hay que pensar que en una pasada, te encuentras con 28 jugadores antagonistas contra 3 en seguridad

Que yo recuerde los quitas mediante cirguias.

**Comment by lharmonyl** [comment]
> 
> 
> > Lo ideal tambien seria algo para poder sacar a los slaves de ese estado, al final hay que pensar que en una pasada, te encuentras con 28 jugadores antagonistas contra 3 en seguridad
> 
> Que yo recuerde los quitas mediante cirguias.
El problema es que nada te indica que esta infectado salvo que vaya sin la cara tapada sale Their features seem unnaturally tight and drawn. 

Aun asi, la pipol de server decia que era meta indentificar slaves con ese metodo, entonces entre eso y que una mascara tapa esa descripcion, no hay manera solida para combatirlos

**Comment by Evankhell561** [comment]
> Aun asi, la pipol de server decia que era meta indentificar slaves con ese metodo, entonces entre eso y que una mascara tapa esa descripcion, no hay manera solida para combatirlos

Eso ya queda de parte de los admis, los de sec pueden tienene el conocimiento de identificar a los antags, solo tienen que pedirles que se quiten la mascara y luego pedirle a medbay que les retire el tumor y decirles en donde está. Nada de esto es meta.

**Comment by lharmonyl** [comment]
> 
> 
> > Aun asi, la pipol de server decia que era meta indentificar slaves con ese metodo, entonces entre eso y que una mascara tapa esa descripcion, no hay manera solida para combatirlos
> 
> Eso ya queda de parte de los admis, los de sec pueden tienene el conocimiento de identificar a los antags, solo tienen que pedirles que se quiten la mascara y luego pedirle a medbay que les retire el tumor y decirles en donde está. Nada de esto es meta.

Creo que deberia verse en HUD medico o con mascara o sin ella para tener un minimo de oportunidad de ganar una ronda shadowling

**Comment by Evankhell561** [comment]
> Creo que deberia verse en HUD medico o con mascara o sin ella para tener un minimo de oportunidad de ganar una ronda shadowling. 

Los si un med no sabe de la existencia de un shadow no deberian tener un hud que reconozca a sus esclavos, basta con que sec declare que todo el que use mascara o se cubra los ojos sera arrestado y ya se soluciona el problema.

**Comment by lharmonyl** [comment]
> 
> 
> > Creo que deberia verse en HUD medico o con mascara o sin ella para tener un minimo de oportunidad de ganar una ronda shadowling.
> 
> Los si un med no sabe de la existencia de un shadow no deberian tener un hud que reconozca a sus esclavos, basta con que sec declare que todo el que use mascara o se cubra los ojos sera arrestado y ya se soluciona el problema.

Esa opcion es tan invalida que no funciona, por el simple hecho de que vas a tener 2 en seguridad vs 1 shadowling y 25 jugadores mas que son slaves, en lo que esposas a 1, se te tiran encima lo 10 que estan ahi, la unica opcion es matar letal a todos los slaves y gente con la cara tapada para frenarlo, es un gamemode para jugarse con mucha seguridad como la revolucion, los slaves no van a rolear, te van a stunear y ya, es cuestion de darle una opcion a combatir el antagonista, como al culto que les das agua bendita y los curas

Añado un post de un usuario de paradise 
https://www.paradisestation.org/forum/topic/13247-shadowling-rebalancing-rework/
que da ideas tambien

**Comment by NervalARS** [comment]
> **Actualmente**: Apagar luces tiene un cd de 15 seg
> 
> **Solucion**: Subirlo a 30

Esto esta hecho así por como dijiste antes el ridículo daño por fuentes de luz. Esta habilidad del changerling es la única forma viable para defenderse, lo que me hace sugerir que el coldown no sea modificado, en su lugar, que la habilidad también afectara a linternas, excepto a luces química (fuego, varitas luminosas, etc...).

**Comment by SagaStars** [comment]
Balance Outdated
